# Generated by Django 2.2.2 on 2019-06-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.TrainLine')),
            ],
        ),
    ]
